version: "3.6"
services:
  contestbot:
    container_name: contestbot
    image: index.docker.io/aleksioprime/contestbot
    command: python app.py
    environment:
      - URL=https://contestbot.aledev.ru/
      - TOKEN=5395574766:AAFbvibum0EMBf106oMaKIFOl2dc8fP1QtQ
      - PORT=5000
    networks:
      - main
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
networks:
  main:
    driver: bridge